import { writeFile } from "node:fs/promises";

import prettier from "prettier";

import { ensureParentDir } from "./ensureParentDir.js";
import { type FilesizeOptions } from "./filesize.js";
import { logComplete } from "./logger.js";
import { prettyFilesize } from "./prettyFilesize.js";

export const GENERATED_FILE_BANNER =
  "// THIS FILE WAS GENERATED BY A SCRIPT AND SHOULD NOT BE UPDATED MANUALLY\n";

export interface GenerateFileOptions {
  format?: boolean;
  banner?: boolean | string;
  fileSize?: boolean | FilesizeOptions;
  contents: string;
  filePath: string;
  getLoggedFileName?: (filePath: string) => string;
}

/**
 * This is used to generate files from scripts with a banner showing that it
 * should not be updated manually as well as automatically formatting the file;
 *
 * @example Simple Example
 * ```tsx
 * await generateFile({
 *   contents: `export const x = 3;
 *
 * export const y = "hello, world!"`,
 *   filePath: "./src/generated/example.ts",
 * });
 * ```
 */
export async function generateFile(
  options: GenerateFileOptions,
): Promise<void> {
  const {
    format = true,
    banner = true,
    fileSize,
    contents,
    filePath,
    getLoggedFileName = (filePath) => filePath.replace(process.cwd() + "/", ""),
  } = options;

  let fileBanner = "";
  if (banner === true) {
    fileBanner = GENERATED_FILE_BANNER;
  } else if (typeof banner === "string") {
    fileBanner = banner;
  }

  let data = `${fileBanner}${contents}`;
  if (format) {
    data = await prettier.format(data, { filepath: filePath });
  }

  await ensureParentDir(filePath);
  await writeFile(filePath, data, "utf8");
  let suffix = "";
  if (fileSize) {
    suffix = ` (${prettyFilesize(data, typeof fileSize === "object" ? fileSize : undefined)})`;
  }

  logComplete(`Wrote "${getLoggedFileName(filePath)}"${suffix}`);
}
