import { type CompileResult, type Options, compileString } from "sass";

import { FILE_URL } from "./constants.js";
import { getPossiblePaths } from "./getPossiblePaths.js";
import { resolveSassImportFromPackageJson } from "./resolveSassImportFromPackageJson.js";

export interface CompileScssOptions {
  code: string;
  load: (filePath: string) => string;
  basePath: string;
  sassOptions?: Options<"sync">;
}

/**
 * Allows you to compile scss in either the node or browser environments with
 * some additional setup.
 *
 * @example Node Example
 * ```ts
 * // start by setting a base path for everything. using process.cwd() is
 * // usually the easiest
 * const basePath = process.cwd();
 * const code = await readFile("./some/path/to/file.scss", 'utf8');
 *
 * const css = compileScss({
 *   code,
 *   // add a synchronous load function
 *   load: (filePath) => readFileSync(filePath, "utf8"),
 *
 *   // add the base path
 *   basePath,
 * });
 * ```
 *
 * @example Browser Example
 * ```ts
 * // the browser example is a bit more difficult as you need to create a
 * // lookup for all the file paths and reference them in the load function
 * // this should be any absolute path other than `/` and unique enough to be
 * // replaced easily
 * const basePath = "/__home__";
 *
 * // NOTE: This can be generated by "abusing" the node API. see the next example
 *
 * const SCSS_LOOKUP: Record<string, string> = {
 *   [`${basePath}/file1.scss`]: "contents of that file",
 *   [`${basePath}/node_modules/dependency-name/package.json`]: JSON.stringify({
 *     exports: {
 *       ".": {
 *         "sass": "./dist/_main.scss"
 *       },
 *     },
 *   }),
 * };
 *
 * const css = compileScss({
 *   code,
 *   load: filePath => {
 *     const contents = SCSS_LOOKUP[filePath];
 *     if (!contents) {
 *       throw new Error("Not found")
 *     }
 *
 *     return contents;
 *   },
 *   basePath,
 * })
 * ```
 *
 * @example Generating SCSS Lookup
 * ```ts
 * const basePath = process.cwd();
 * const browserBasePath = "/__home__";
 * const browserOutFilePath = "./src/generated/scssLookup.ts";
 *
 * const lookup: Record<string, string> = {};
 * compileScss({
 *   code: "@use 'everything';",
 *   load: (filePath) => {
 *     const contents = readFileSync(filePath, "utf8");
 *     const browserName = filePath.replace(basePath, "/__home__");
 *     if (filePath.endsWith("package.json")) {
 *       const parsed = JSON.parse(contents);
 *       assertScssResolvePackageJson(parsed);
 *
 *       // can trim down the exports if needed
 *       lookup[browserName] = JSON.stringify({
 *         exports: parsed.exports,
 *         sass: parsed.sass,
 *         main: parsed.main,
 *       });
 *     } else {
 *       // can trim down the contents if needed. like removing comments
 *       lookup[browserName] = contents;
 *     }
 *
 *     return contents;
 *   },
 *   basePath,
 * });
 *
 * const lookupString = JSON.stringify(lookup);
 * await writeFile(
 *   browserOutFilePath,
 *   await format(`
 * export const SCSS_LOOKUP: Record<string, string> = ${lookupString}
 * `,
 *     { parser: "typescript" }
 *   ),
 *   'utf8'
 * );
 * ```
 */
export function compileScss(options: CompileScssOptions): CompileResult {
  const { code, load, basePath, sassOptions } = options;

  return compileString(code, {
    ...sassOptions,
    importers: [
      {
        canonicalize(url) {
          // if it's a relative path, let sass handle it itself.
          if (url.startsWith(".")) {
            return null;
          }

          let currentUrl = url;
          if (currentUrl.startsWith(FILE_URL)) {
            currentUrl = currentUrl.replace(FILE_URL, "");
          }
          currentUrl = currentUrl.replace(basePath + "/", "");

          const resolved = resolveSassImportFromPackageJson({
            url: currentUrl,
            load,
            basePath,
          });
          if (resolved) {
            return new URL(resolved, FILE_URL);
          }

          const possiblePaths = getPossiblePaths(`${basePath}/${currentUrl}`);
          for (const path of possiblePaths) {
            try {
              load(path);
              return new URL(path, FILE_URL);
            } catch {
              continue;
            }
          }
          return null;
        },
        load(canonicalUrl) {
          const filePath = canonicalUrl.pathname;
          const contents = load(filePath);

          return {
            syntax: "scss",
            contents,
          };
        },
      },
    ],
  });
}
