import htmlMinify from "html-minifier-terser";

import { IS_PRODUCTION } from "../constants.js";

export function htmlPlugin(eleventyConfig) {
  eleventyConfig.addTransform("html-minify", (content, path) => {
    if (!IS_PRODUCTION || !path?.endsWith(".html")) {
      return content;
    }

    return htmlMinify.minify(content, {
      collapseBooleanAttributes: true,
      collapseWhitespace: true,
      decodeEntities: true,
      includeAutoGeneratedTags: false,
      removeComments: true,
    });
  });
}
